name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install hidapi
      shell: bash
      run: sudo apt install libhidapi-hidraw0 libhidapi-dev
    - name: Checkout submodule
      shell: bash
      run: git submodule init && git submodule update
    
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        stable: true

    - name: Configure CMake
      shell: bash
      run: cmake .

    - name: Build daemon
      shell: bash
      run: cmake --build .
    
    - name: Build controller
      shell: bash
      working-directory: ${{github.workspace}}/rgbctl
      run: go build
      
